name: PR test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: lint & format
        run: |
          npm run lint
          npx prettier --check .
        env:
          CI: true
      - name: test
        run: npm run test
        env:
          CI: true
